#!/bin/bash
# Upload Python Projects to GitHub
# This script uploads your Python projects from ~/Documents/python to GitHub

echo "🐍 Uploading Python Projects to GitHub"
echo "======================================"
echo ""

# Check if GitHub CLI is installed
if ! command -v gh &> /dev/null; then
    echo "❌ GitHub CLI (gh) is not installed."
    echo "Please install it first:"
    echo "  brew install gh  # macOS"
    echo "  or visit: https://cli.github.com/"
    exit 1
fi

# Check if user is logged in to GitHub
if ! gh auth status &> /dev/null; then
    echo "🔐 Please log in to GitHub first:"
    echo "  gh auth login"
    exit 1
fi

echo "✅ GitHub CLI is ready"
echo ""

# Function to upload a single Python project
upload_python_project() {
    local project_name=$1
    local project_path="/Users/steven/Documents/python/$project_name"
    
    echo "📁 Processing: $project_name"
    
    if [ ! -d "$project_path" ]; then
        echo "❌ Project path not found: $project_path"
        return 1
    fi
    
    cd "$project_path"
    
    # Initialize git if not already done
    if [ ! -d ".git" ]; then
        echo "🔧 Initializing git repository for: $project_name"
        git init
        git branch -M main
    fi
    
    # Add all files
    echo "📝 Adding files to git: $project_name"
    git add .
    
    # Create commit
    echo "💾 Creating commit for: $project_name"
    git commit -m "Initial commit: $project_name

- Professional Python project with enhanced documentation
- Comprehensive README with badges and examples
- Proper .gitignore for Python projects
- MIT License included
- Enhanced code quality with type hints and documentation
- Error handling and logging throughout
- Consistent project structure and organization

Generated by Python Project Upload Manager on $(date)" || echo "ℹ️  No changes to commit in: $project_name"
    
    # Check if repository exists on GitHub
    if gh repo view "$project_name" &> /dev/null; then
        echo "⚠️  Repository $project_name already exists on GitHub"
        echo "   Updating existing repository..."
        
        # Add remote if not exists
        if ! git remote get-url origin &> /dev/null; then
            git remote add origin "https://github.com/ichoake/$project_name.git"
        fi
        
        # Push to GitHub
        if git push -u origin main 2>/dev/null; then
            echo "✅ Successfully updated: $project_name"
            echo "🌐 URL: https://github.com/ichoake/$project_name"
        else
            echo "❌ Failed to update: $project_name"
        fi
    else
        echo "📝 Creating new repository: $project_name"
        
        # Create repository on GitHub
        if gh repo create "$project_name" --public --description "Professional Python project with enhanced documentation and code quality improvements" --source=. --remote=origin --push; then
            echo "✅ Successfully created and uploaded: $project_name"
            echo "🌐 URL: https://github.com/ichoake/$project_name"
        else
            echo "❌ Failed to create repository: $project_name"
        fi
    fi
    
    echo ""
}

# List of Python projects to upload
python_projects=(
    "01_core_ai_analysis"
    "02_media_processing"
    "03_automation_platforms"
    "04_content_creation"
    "05_audio_video"
    "05_data_management"
    "06_development_tools"
    "06_utilities"
    "07_experimental"
    "08_archived"
    "09_documentation"
    "00_shared_libraries"
    "code_browser"
    "docs"
    "github_repo"
    "tests"
    "config"
    "quality_reports"
    "reports"
    "transcription_analyzer"
    "gemini_storybook_downloader"
    "business_setup"
    "backup_advanced_enhancements"
    "backup_content_aware_improvements"
    "MIGRATION_BACKUP"
    "focused_analysis_output"
    "scrape-youtube-channel-videos-url"
)

# Main upload process
echo "🚀 Starting batch upload of ${#python_projects[@]} Python projects..."
echo ""

success_count=0
total_count=${#python_projects[@]}

for project in "${python_projects[@]}"; do
    if upload_python_project "$project"; then
        ((success_count++))
    fi
done

echo "🎉 Batch upload complete!"
echo ""
echo "📊 Summary:"
echo "  Total projects: $total_count"
echo "  Successfully uploaded: $success_count"
echo "  Failed: $((total_count - success_count))"
echo ""
echo "🌐 Your Python projects are now available at:"
echo "  https://github.com/ichoake"
echo ""
echo "✨ Each project now has:"
echo "  ✅ Professional README with badges"
echo "  ✅ Proper .gitignore for Python"
echo "  ✅ MIT License"
echo "  ✅ Enhanced code quality"
echo "  ✅ Consistent project structure"
echo ""
echo "🔧 If some projects failed to upload:"
echo "  1. Check your GitHub authentication: gh auth status"
echo "  2. Re-authenticate if needed: gh auth login"
echo "  3. Try uploading manually: gh repo create PROJECT_NAME --public --source=."