#!/bin/bash
# Upload Main Python Projects to GitHub
# This script uploads your main Python projects to GitHub

echo "🐍 Uploading Main Python Projects to GitHub"
echo "==========================================="
echo ""

# Check if GitHub CLI is installed
if ! command -v gh &> /dev/null; then
    echo "❌ GitHub CLI (gh) is not installed."
    echo "Please install it first:"
    echo "  brew install gh  # macOS"
    echo "  or visit: https://cli.github.com/"
    exit 1
fi

# Check if user is logged in to GitHub
if ! gh auth status &> /dev/null; then
    echo "🔐 Please log in to GitHub first:"
    echo "  gh auth login"
    exit 1
fi

echo "✅ GitHub CLI is ready"
echo ""

# Function to upload a single project
upload_project() {
    local project_name=$1
    local project_path="/Users/steven/Documents/python/$project_name"
    
    echo "📁 Processing: $project_name"
    
    if [ ! -d "$project_path" ]; then
        echo "❌ Project path not found: $project_path"
        return 1
    fi
    
    cd "$project_path"
    
    # Initialize git if not already done
    if [ ! -d ".git" ]; then
        echo "🔧 Initializing git repository for: $project_name"
        git init
        git branch -M main
    fi
    
    # Add all files
    echo "📝 Adding files to git: $project_name"
    git add .
    
    # Create commit
    echo "💾 Creating commit for: $project_name"
    git commit -m "Initial commit: $project_name

- Professional Python project with enhanced documentation
- Comprehensive README with badges and examples
- Proper .gitignore for Python projects
- MIT License included
- Enhanced code quality with type hints and documentation
- Error handling and logging throughout
- Consistent project structure and organization

Generated by Python Project Upload Manager on $(date)" || echo "ℹ️  No changes to commit in: $project_name"
    
    # Check if repository exists on GitHub
    if gh repo view "$project_name" &> /dev/null; then
        echo "⚠️  Repository $project_name already exists on GitHub"
        echo "   Updating existing repository..."
        
        # Add remote if not exists
        if ! git remote get-url origin &> /dev/null; then
            git remote add origin "https://github.com/ichoake/$project_name.git"
        fi
        
        # Push to GitHub
        if git push -u origin main 2>/dev/null; then
            echo "✅ Successfully updated: $project_name"
            echo "🌐 URL: https://github.com/ichoake/$project_name"
        else
            echo "❌ Failed to update: $project_name"
        fi
    else
        echo "📝 Creating new repository: $project_name"
        
        # Create repository on GitHub
        if gh repo create "$project_name" --public --description "Professional Python project with enhanced documentation and code quality improvements" --source=. --remote=origin --push; then
            echo "✅ Successfully created and uploaded: $project_name"
            echo "🌐 URL: https://github.com/ichoake/$project_name"
        else
            echo "❌ Failed to create repository: $project_name"
        fi
    fi
    
    echo ""
}

# Main Python projects to upload (your core projects)
main_projects=(
    "python-projects-collection"
    "ai-analysis-tools"
    "media-processing-suite"
    "automation-platforms"
    "content-creation-tools"
    "data-management-utilities"
    "development-tools"
    "experimental-projects"
    "shared-libraries"
    "documentation-tools"
    "quality-monitoring"
    "github-repo-manager"
    "python-code-enhancer"
    "github-repo-analyzer"
)

# Main upload process
echo "🚀 Starting upload of ${#main_projects[@]} main Python projects..."
echo ""

success_count=0
total_count=${#main_projects[@]}

for project in "${main_projects[@]}"; do
    if upload_project "$project"; then
        ((success_count++))
    fi
done

echo "🎉 Main projects upload complete!"
echo ""
echo "📊 Summary:"
echo "  Total projects: $total_count"
echo "  Successfully uploaded: $success_count"
echo "  Failed: $((total_count - success_count))"
echo ""
echo "🌐 Your Python projects are now available at:"
echo "  https://github.com/ichoake"